/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "deeichvgibhpbrowhaiq"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRlZWljaHZnaWJocGJyb3doYWlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyNzQxMDgsImV4cCI6MjA3MDg1MDEwOH0.edQcNr-MnsLY2D6QtxgUy-1so9CvCxwwPBt4v881M9U"